# Generated by Django 2.0 on 2017-12-04 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_auto_20160831_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='prenotazioni.UtentePrenotazioni'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='viaggio',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tam.Viaggio'),
        ),
        migrations.AlterField(
            model_name='utenteprenotazioni',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
