# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2024-06-30 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_auto_20160831_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='note_arrivo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Dettagli volo'),
        ),
    ]
