---
version: 1
disable_existing_loggers: no
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    main_formatter:
        format: '%(levelname)s:%(name)s: %(message)s (%(asctime)s; %(filename)s:%(lineno)d)'
        datefmt: '%Y-%m-%d %H:%M:%S'
filters:
    require_debug_false:
        (): django.utils.log.RequireDebugFalse
    require_debug_true:
        (): django.utils.log.RequireDebugTrue

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: main_formatter

    production_file:
        level: DEBUG
        class: logging.handlers.TimedRotatingFileHandler
        filename: logs/main.log
        formatter: main_formatter
        filters: [require_debug_false]

        when: midnight
        utc: True
        delay: True
        backupCount: 7
        encoding: utf8

    mail_admins:
        level: ERROR
        filters: [require_debug_false]
        class: django.utils.log.AdminEmailHandler

    'null':
        class: logging.NullHandler

loggers:
    tam:
        level: DEBUG
        
    django.channels:
        level: DEBUG

    daphne.server:
        level: WARNING

    django.server:
        level: WARNING
        handlers: ['null']

root:
    level: INFO
    handlers: [mail_admins, console, production_file]
