# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tam", "0003_auto_20160501_0216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="commissione",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Quota consorzio",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dati",
            field=models.TextField(
                blank=True, help_text="Stampati nelle fattura conducente", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fatturazione",
            field=models.BooleanField(
                default=False, verbose_name="Fatturazione richiesta"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="incassato_albergo",
            field=models.BooleanField(default=False, verbose_name="Conto fine mese"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="listino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tam.Listino",
                verbose_name="Listino cliente",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="Nome cliente"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="pagamento_differito",
            field=models.BooleanField(
                default=False, verbose_name="Fatturazione esente IVA"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo",
            field=models.CharField(
                choices=[("H", "Hotel"), ("A", "Agenzia"), ("D", "Ditta")],
                max_length=1,
                verbose_name="Tipo cliente",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo_commissione",
            field=models.CharField(
                choices=[("F", "€"), ("P", "%")],
                default="F",
                max_length=1,
                verbose_name="Tipo di quota",
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="classifica_iniziale_diurni",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Supplementari diurni",
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="classifica_iniziale_doppiPadova",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Doppi Padova"
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="classifica_iniziale_long",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Venezia"
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="classifica_iniziale_medium",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Padova"
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="classifica_iniziale_notturni",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Supplementari notturni",
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="classifica_iniziale_prezzoDoppiVenezia",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valore Doppi Venezia",
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="classifica_iniziale_puntiDoppiVenezia",
            field=models.IntegerField(default=0, verbose_name="Punti Doppi Venezia"),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="dati",
            field=models.TextField(
                blank=True, help_text="Stampati nelle fattura conducente", null=True
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="emette_ricevute",
            field=models.BooleanField(
                default=True,
                help_text="Il conducente può emettere fatture senza IVA?",
                verbose_name="Emette senza IVA?",
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="nick",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Sigla"
            ),
        ),
        migrations.AlterField(
            model_name="conducente",
            name="nome",
            field=models.CharField(max_length=40, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="luogo",
            name="bacino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tam.Bacino",
                verbose_name="Bacino di appartenenza",
            ),
        ),
        migrations.AlterField(
            model_name="luogo",
            name="nome",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Località\xa0"
            ),
        ),
        migrations.AlterField(
            model_name="luogo",
            name="speciale",
            field=models.CharField(
                choices=[("-", "-"), ("A", "Aeroporto"), ("S", "Stazione")],
                default="",
                max_length=1,
                verbose_name="Luogo particolare",
            ),
        ),
        migrations.AlterField(
            model_name="prezzolistino",
            name="commissione",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                null=True,
                verbose_name="Quota consorzio",
            ),
        ),
        migrations.AlterField(
            model_name="prezzolistino",
            name="flag_fatturazione",
            field=models.CharField(
                choices=[
                    ("S", "Fatturazione richiesta"),
                    ("N", "Fatturazione non richiesta"),
                    ("-", "Usa impostazioni del cliente"),
                ],
                default="-",
                max_length=1,
                verbose_name="Fatturazione forzata",
            ),
        ),
        migrations.AlterField(
            model_name="prezzolistino",
            name="max_pax",
            field=models.IntegerField(default=4, verbose_name="Pax Massimi"),
        ),
        migrations.AlterField(
            model_name="prezzolistino",
            name="tipo_commissione",
            field=models.CharField(
                choices=[("F", "€"), ("P", "%")],
                default="F",
                max_length=1,
                verbose_name="Tipo di quota",
            ),
        ),
        migrations.AlterField(
            model_name="prezzolistino",
            name="tipo_servizio",
            field=models.CharField(
                choices=[("T", "Taxi"), ("C", "Collettivo")], default="T", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="profiloutente",
            name="luogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tam.Luogo",
                verbose_name="Luogo di partenza",
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="annullato",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Corsa annullata"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="cartaDiCredito",
            field=models.BooleanField(
                default=False, verbose_name="Pagamento con carta di credito"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="commissione",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Quota consorzio",
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="conducente_confermato",
            field=models.BooleanField(
                default=False, verbose_name="Conducente confermato"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="conducente_richiesto",
            field=models.BooleanField(
                default=False, verbose_name="Escluso dai supplementari"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="data",
            field=models.DateTimeField(db_index=True, verbose_name="Data e ora"),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="data_padre",
            field=models.DateTimeField(
                db_index=True,
                editable=False,
                null=True,
                verbose_name="Data e ora padre",
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="esclusivo",
            field=models.BooleanField(default=True, verbose_name="Servizio taxi"),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="fatturazione",
            field=models.BooleanField(
                default=False, verbose_name="Fatturazione richiesta"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="id_padre",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, null=True, verbose_name="ID Gruppo"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="incassato_albergo",
            field=models.BooleanField(default=False, verbose_name="Conto fine mese"),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="is_prenotazione",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Derivato da prenotazione"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="km_conguagliati",
            field=models.IntegerField(
                blank=True,
                default=0,
                editable=False,
                null=True,
                verbose_name="Km conguagliati",
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="pagamento_differito",
            field=models.BooleanField(
                default=False, verbose_name="Fatturazione esente IVA"
            ),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="tipo_commissione",
            field=models.CharField(
                choices=[("F", "€"), ("P", "%")],
                default="F",
                max_length=1,
                verbose_name="Tipo di quota",
            ),
        ),
    ]
