# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tam", "0005_viaggio_additional_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="conducente",
            name="has_bus",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="viaggio",
            name="prezzo_sosta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Prezzo sosta addizionale",
            ),
        ),
    ]
