# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-12-11 21:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0007_auto_20190525_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='luogo',
            name='anticipo_servizio',
            field=models.IntegerField(default=20, validators=(django.core.validators.MinValueValidator(0),), verbose_name='Anticipo servizio'),
        ),
    ]
