# Generated by Django 2.0 on 2018-01-19 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0008_conducente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducente',
            name='user',
            field=models.OneToOneField(limit_choices_to={'prenotazioni__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
