# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2022-04-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tam", "0008_luogo_anticipo_servizio"),
    ]

    operations = [
        migrations.AddField(
            model_name="conducente",
            name="classifica_iniziale_fatture_corse",
            field=models.IntegerField(
                default=0, verbose_name="Classifica fatture - corse"
            ),
        ),
        migrations.AddField(
            model_name="conducente",
            name="classifica_iniziale_fatture_valore",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Classifica fatture - valore",
            ),
        ),
        migrations.AlterField(
            model_name="luogo",
            name="nome",
            field=models.CharField(max_length=25, unique=True, verbose_name="Località"),
        ),
    ]
