# Generated by Django 2.0.4 on 2023-01-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0009_auto_20220415_1857'),
        ('tam', '0009_auto_20180119_2007'),
    ]

    operations = [
    ]
