# Generated by Django 3.1.14 on 2023-02-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0010_merge_20230118_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducente',
            name='classifica_iniziale_fatture_corse',
            field=models.IntegerField(default=0, editable=False, verbose_name='Classifica fatture - corse'),
        ),
        migrations.AlterField(
            model_name='conducente',
            name='classifica_iniziale_fatture_valore',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Classifica fatture - valore'),
        ),
    ]
