# Generated by Django 4.0.9 on 2023-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0011_auto_20230207_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducente',
            name='classifica_iniziale_fatture_corse',
            field=models.IntegerField(default=0, verbose_name='Classifica fatture - corse'),
        ),
        migrations.AlterField(
            model_name='conducente',
            name='classifica_iniziale_fatture_valore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Classifica fatture - valore'),
        ),
    ]
