# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(db_index=True)),
                ('user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('action_type', models.CharField(choices=[(b'A', b'Creazione'), (b'M', b'Modifica'), (b'D', b'Cancellazione'), (b'L', b'Login'), (b'O', b'Logout'), (b'K', b'Archiviazione'), (b'F', b'Appianamento'), (b'X', b'Export Excel')], max_length=1)),
                ('modelName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('instance_id', models.IntegerField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True)),
                ('hilight', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data'],
                'verbose_name_plural': 'Azioni',
            },
        ),
    ]
