# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modellog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("A", "Creazione"),
                    ("M", "Modifica"),
                    ("D", "Cancellazione"),
                    ("L", "Login"),
                    ("O", "Logout"),
                    ("K", "Archiviazione"),
                    ("F", "Appianamento"),
                    ("X", "Export Excel"),
                ],
                max_length=1,
            ),
        ),
    ]
