# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='doc_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
