# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fatturazione", "0002_fattura_doc_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fattura",
            name="doc_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
