# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatturazione", "0003_auto_20190525_1951"),
    ]

    operations = [
        migrations.AddField(
            model_name="fattura",
            name="pagata",
            field=models.BooleanField(default=False),
        ),
    ]
