# Generated by Django 2.0.4 on 2023-01-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0002_auto_20171204_2350'),
        ('fatturazione', '0004_fattura_pagata'),
    ]

    operations = [
    ]
