# Generated by Django 2.0 on 2017-12-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamArchive', '0002_auto_20160831_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaggioarchive',
            options={'ordering': ['data'], 'permissions': (('flat', "Esegue l'appianamento"), ('archive', "Esegue l'archiviazione"), ('view', "Visualizza l'archiviazione")), 'verbose_name_plural': 'Archivi'},
        ),
        migrations.AlterField(
            model_name='viaggioarchive',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tamArchive.ViaggioArchive'),
        ),
    ]
