# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-25 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamArchive', '0002_auto_20160831_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaggioarchive',
            options={'ordering': ['data'], 'permissions': (('flat', "Esegue l'appianamento"), ('archive', "Esegue l'archiviazione"), ('view', "Visualizza l'archiviazione")), 'verbose_name_plural': 'Archivi'},
        ),
    ]
