# Generated by Django 2.0.4 on 2023-01-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamArchive', '0003_auto_20190525_1951'),
        ('tamArchive', '0003_auto_20171204_2350'),
    ]

    operations = [
    ]
