# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendariopresenze", "0002_auto_20160501_0216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="type",
            field=models.IntegerField(choices=[(1, "Ferie"), (2, "Riposo")]),
        ),
    ]
