# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendariopresenze', '0003_auto_20160831_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ferie'), (2, 'Riposo'), (3, 'Ufficio')]),
        ),
    ]
