# Generated by Django 2.0 on 2017-12-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendariopresenze', '0005_auto_20160924_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='conducente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='tam.Conducente'),
        ),
    ]
