# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmessage",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Messaggio visibile"),
        ),
        migrations.AlterField(
            model_name="boardmessage",
            name="date",
            field=models.DateTimeField(verbose_name="Data di inserimento"),
        ),
        migrations.AlterField(
            model_name="boardmessage",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Messaggio"),
        ),
    ]
